# Generated by Django 3.1 on 2020-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_add',
            field=models.BooleanField(default=True),
        ),
    ]
