# Generated by Django 3.1 on 2020-08-24 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer_id', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='address_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='bill_id',
            field=models.IntegerField(default=0),
        ),
    ]
